In [23]:
import pandas as pd
import numpy as np
import yfinance as yfin
import ta

In [24]:
df = yfin.download("BTC-USD", start="2020-01-01", end="2026-01-01")
df

[*********************100%***********************]  1 of 1 completed

Price,Close,High,Low,Open,Volume
Ticker,BTC-USD,BTC-USD,BTC-USD,BTC-USD,BTC-USD
Date,,,,,
2020-01-01,7200.174316,7254.330566,7174.944336,7194.892090,18565664997
2020-01-02,6985.470215,7212.155273,6935.270020,7202.551270,20802083465
2020-01-03,7344.884277,7413.715332,6914.996094,6984.428711,28111481032
2020-01-04,7410.656738,7427.385742,7309.514160,7345.375488,18444271275
2020-01-05,7411.317383,7544.497070,7400.535645,7410.451660,19725074095
...,...,...,...,...,...
2025-12-27,87802.156250,87874.781250,87182.976562,87301.429688,13741199310
2025-12-28,87835.835938,87986.890625,87394.953125,87799.343750,15156557929
2025-12-29,87138.140625,90299.156250,86717.914062,87835.789062,48411625849
2025-12-30,88430.132812,89297.937500,86735.546875,87134.351562,35586356225
2025-12-31,87508.828125,89080.289062,87130.562500,88429.585938,33830210616

In [26]:
df.columns = df.columns.droplevel(1)

In [28]:
# EMAs
df['EMA_5'] = ta.trend.ema_indicator(close=df['Close'], window=5, fillna=True) / df['Close']
df['EMA_20'] = ta.trend.ema_indicator(close=df['Close'], window=20, fillna=True) / df['Close']
df['EMA_50'] = ta.trend.ema_indicator(close=df['Close'], window=50, fillna=True) / df['Close']
df['EMA_100'] = ta.trend.ema_indicator(close=df['Close'], window=100, fillna=True) / df['Close']

# índice de fuerza relativa
df['RSI'] = ta.momentum.rsi(close=df['Close'], fillna=True)

# rango verdadero medio
df['ATR'] = ta.volatility.average_true_range(
    high=df['High'],
    low=df['Low'],
    close=df['Close'],
    fillna=True
)

# rango de porcentaje de Williams
df['Williams'] = ta.momentum.williams_r(
    high=df['High'],
    low=df['Low'],
    close=df['Close'],
    fillna=True
)
df

Price,Close,High,Low,Open,Volume,EMA_5,EMA_20,EMA_50,EMA_100,RSI,ATR,Williams
Date,,,,,,,,,,,,
2020-01-01,7200.174316,7254.330566,7174.944336,7194.892090,18565664997,1.000000,1.000000,1.000000,1.000000,100.000000,0.000000,-68.218694
2020-01-02,6985.470215,7212.155273,6935.270020,7202.551270,20802083465,1.020491,1.027809,1.029530,1.030127,0.000000,0.000000,-84.266248
2020-01-03,7344.884277,7413.715332,6914.996094,6984.428711,28111481032,0.980369,0.979655,0.979969,0.980121,64.320963,0.000000,-13.801564
2020-01-04,7410.656738,7427.385742,7309.514160,7345.375488,18444271275,0.981112,0.973726,0.972398,0.971988,68.334871,0.000000,-3.264899
2020-01-05,7411.317383,7544.497070,7400.535645,7410.451660,19725074095,0.987350,0.976150,0.973397,0.972457,68.373359,0.000000,-21.156391
...,...,...,...,...,...,...,...,...,...,...,...,...
2025-12-27,87802.156250,87874.781250,87182.976562,87301.429688,13741199310,0.997804,1.008144,1.053045,1.117371,44.616331,2800.162979,-44.509460
2025-12-28,87835.835938,87986.890625,87394.953125,87799.343750,15156557929,0.998281,1.007019,1.050577,1.114627,44.754060,2642.432587,-43.954204
2025-12-29,87138.140625,90299.156250,86717.914062,87835.789062,48411625849,1.004183,1.013646,1.056676,1.121105,42.401671,2709.490416,-55.456666
2025-12-30,88430.132812,89297.937500,86735.546875,87134.351562,35586356225,0.993007,0.998947,1.039620,1.102651,47.866453,2698.983288,-34.156407
2025-12-31,87508.828125,89080.289062,87130.562500,88429.585938,33830210616,1.002308,1.008562,1.048582,1.111998,44.615736,2645.464950,-49.345375